/* Generated by Yosys 0.39 (git sha1 00338082b, g++ 13.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -Os) */

(* top =  1  *)
module cpld(RD_n, WR_n, IORQ_n, MREQ_n, MAD_n, MEI, A, D, STRUKT_n, SEG_on, AD13, AD14, AD15, CS_n, RAM_WR_n, MEO);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input [15:0] A;
  wire [15:0] A;
  output AD13;
  wire AD13;
  output AD14;
  wire AD14;
  output AD15;
  wire AD15;
  output CS_n;
  wire CS_n;
  input [7:0] D;
  wire [7:0] D;
  input IORQ_n;
  wire IORQ_n;
  input MAD_n;
  wire MAD_n;
  input MEI;
  wire MEI;
  output MEO;
  wire MEO;
  input MREQ_n;
  wire MREQ_n;
  output RAM_WR_n;
  wire RAM_WR_n;
  input RD_n;
  wire RD_n;
  output SEG_on;
  wire SEG_on;
  output STRUKT_n;
  wire STRUKT_n;
  input WR_n;
  wire WR_n;
  wire [7:0] control;
  DL004D_6x1NOT _20_ (
    .A(A[6]),
    .Y(_01_)
  );
  DL004D_6x1NOT _21_ (
    .A(WR_n),
    .Y(_02_)
  );
  DL004D_6x1NOT _22_ (
    .A(A[15]),
    .Y(_03_)
  );
  DL004D_6x1NOT _23_ (
    .A(MEI),
    .Y(_04_)
  );
  DL004D_6x1NOT _24_ (
    .A(MREQ_n),
    .Y(_05_)
  );
  DL032D_4x1OR2 _25_ (
    .A(MAD_n),
    .B(IORQ_n),
    .Y(_06_)
  );
  DL032D_4x1OR2 _26_ (
    .A(A[1]),
    .B(A[0]),
    .Y(_07_)
  );
  DL002D_4x1NOR2 _27_ (
    .A(_06_),
    .B(_07_),
    .Y(_08_)
  );
  DL002D_4x1NOR2 _28_ (
    .A(A[9]),
    .B(A[8]),
    .Y(_09_)
  );
  DL011D_3x1AND3 _29_ (
    .A(_01_),
    .B(A[7]),
    .C(_09_),
    .Y(_10_)
  );
  DL002D_4x1NOR2 _30_ (
    .A(A[3]),
    .B(A[2]),
    .Y(_11_)
  );
  DL002D_4x1NOR2 _31_ (
    .A(A[5]),
    .B(A[4]),
    .Y(_12_)
  );
  DL020D_2x1NAND4 _32_ (
    .A(_08_),
    .B(_10_),
    .C(_11_),
    .D(_12_),
    .Y(_13_)
  );
  DL032D_4x1OR2 _33_ (
    .A(RD_n),
    .B(_13_),
    .Y(STRUKT_n)
  );
  DL000D_4x1NAND2 _34_ (
    .A(_02_),
    .B(control[1]),
    .Y(RAM_WR_n)
  );
  DL086D_4x1XOR2 _35_ (
    .A(A[14]),
    .B(control[6]),
    .Y(_14_)
  );
  DL086D_4x1XOR2 _36_ (
    .A(A[13]),
    .B(control[5]),
    .Y(_15_)
  );
  DL002D_4x1NOR2 _37_ (
    .A(_14_),
    .B(_15_),
    .Y(_16_)
  );
  DL011D_3x1AND3 _38_ (
    .A(control[0]),
    .B(MEI),
    .C(_05_),
    .Y(_17_)
  );
  DL086D_4x1XOR2 _39_ (
    .A(_03_),
    .B(control[7]),
    .Y(_18_)
  );
  DL011D_3x1AND3 _40_ (
    .A(_16_),
    .B(_17_),
    .C(_18_),
    .Y(_19_)
  );
  DL004D_6x1NOT _41_ (
    .A(_19_),
    .Y(CS_n)
  );
  DL002D_4x1NOR2 _42_ (
    .A(WR_n),
    .B(_13_),
    .Y(_00_)
  );
  DL002D_4x1NOR2 _43_ (
    .A(_04_),
    .B(_19_),
    .Y(MEO)
  );
  DL374D_8x1DFF _44_ (
    .CLK(_00_),
    .D(D[0]),
    .Q(control[0])
  );
  DL374D_8x1DFF _45_ (
    .CLK(_00_),
    .D(D[1]),
    .Q(control[1])
  );
  DL374D_8x1DFF _46_ (
    .CLK(_00_),
    .D(D[2]),
    .Q(control[2])
  );
  DL374D_8x1DFF _47_ (
    .CLK(_00_),
    .D(D[3]),
    .Q(control[3])
  );
  DL374D_8x1DFF _48_ (
    .CLK(_00_),
    .D(D[4]),
    .Q(control[4])
  );
  DL374D_8x1DFF _49_ (
    .CLK(_00_),
    .D(D[5]),
    .Q(control[5])
  );
  DL374D_8x1DFF _50_ (
    .CLK(_00_),
    .D(D[6]),
    .Q(control[6])
  );
  DL374D_8x1DFF _51_ (
    .CLK(_00_),
    .D(D[7]),
    .Q(control[7])
  );
  assign AD13 = control[2];
  assign AD14 = control[3];
  assign AD15 = control[4];
  assign SEG_on = control[0];
endmodule
